#!/usr/bin/env python

import signal

from viessmanntools import ViessmannToolsConfig, VclientToMqtt

def exit_handler(sig, frame):
    vclient_to_mqtt.stop()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, exit_handler)
    signal.signal(signal.SIGTERM, exit_handler)

    with VclientToMqtt(ViessmannToolsConfig.get_config("/etc/viessmanntools.conf")) as vclient_to_mqtt:
        vclient_to_mqtt.run()
