#!/usr/bin/env python

import signal

from viessmanntools import VclientToMqtt

def exit_handler(sig, frame):
    vclient_to_mqtt.stop()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, exit_handler)
    signal.signal(signal.SIGTERM, exit_handler)

    with VclientToMqtt() as vclient_to_mqtt:
        vclient_to_mqtt.run()
