#!/usr/bin/env python3

from viessmanntools.config import ViessmannToolsConfig
from viessmanntools.vclienttomqtt import VclientToMqtt


def main():
    config = ViessmannToolsConfig.get_config("/etc/viessmanntools.conf")
    vclient_to_mqtt = VclientToMqtt(config)
    vclient_to_mqtt.loop()


if __name__ == "__main__":
    main()
