#!/usr/bin/env python3

from viessmanntools.config import ViessmannToolsConfig
from viessmanntools.vitoreset import VitoReset


def main():
    config = ViessmannToolsConfig.get_config("/etc/viessmanntools.conf")
    vito_reset = VitoReset(config)
    vito_reset.loop()


if __name__ == "__main__":
    main()
